//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OccupOSMonitor
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntermediateHwMedadata
    {
        public IntermediateHwMedadata()
        {
            this.SensorDatas = new HashSet<SensorData>();
        }
    
        public int Id { get; set; }
        public string ExternalId { get; set; }
        public string DepartmentName { get; set; }
        public string BuildingName { get; set; }
        public System.DateTime updatedAt { get; set; }
        public System.DateTime createdAt { get; set; }
        public int updaterId { get; set; }
        public int creatorId { get; set; }
    
        public virtual ICollection<SensorData> SensorDatas { get; set; }
    }
}
