//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OccupOSMonitor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OccupOSContext : DbContext
    {
        public OccupOSContext()
            : base("name=OccupOSContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SensorData> SensorDatas { get; set; }
        public DbSet<SensorMetadata> SensorMetadatas1 { get; set; }
        public DbSet<IntermediateHwMedadata> IntermediateHwMedadatas { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
