//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OccupOSMonitor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorData
    {
        public int Id { get; set; }
        public int SensorMetadataId { get; set; }
        public int IntermediateHwMedadataId { get; set; }
        public string MeasuredData { get; set; }
        public System.DateTime updatedAt { get; set; }
        public System.DateTime createdAt { get; set; }
        public int updaterId { get; set; }
        public int creatorId { get; set; }
    
        public virtual SensorMetadata SensorMetadata { get; set; }
        public virtual IntermediateHwMedadata IntermediateHwMedadata { get; set; }
    }
}
